github-ci.ymlを変更してECRにプッシュ8

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -92,7 +92,7 @@ jobs:
         run: |
           set -e
           echo "Describing current task definition..."
-          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ogata-cloudformation-task) || { echo "Failed to describe task definition"; exit 1; }
+          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ogata-dummy-task-family) || { echo "Failed to describe task definition"; exit 1; }
           echo "Current task definition described successfully."
           NEW_TASK_DEF=$(echo $TASK_DEFINITION | jq --arg IMAGE_URI "${{ steps.login-ecr.outputs.registry }}/ogata-cloudformation-template:latest" '.taskDefinition | .containerDefinitions[0].image=$IMAGE_URI | .cpu="512" | .memory="1024" | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
           echo $NEW_TASK_DEF > new-task-def.json
