github-ci.ymlを変更してECRにプッシュ7

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -90,10 +90,15 @@ jobs:
       - name: Register new task definition
         id: task-def
         run: |
-          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ogata-dummy-task-family)
-          NEW_TASK_DEF=$(echo $TASK_DEFINITION | jq --arg IMAGE_URI "${{ steps.login-ecr.outputs.registry }}/ogata-cloudformation-template:latest" '.taskDefinition | .containerDefinitions[0].image=$IMAGE_URI | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
+          set -e
+          echo "Describing current task definition..."
+          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ogata-cloudformation-task) || { echo "Failed to describe task definition"; exit 1; }
+          echo "Current task definition described successfully."
+          NEW_TASK_DEF=$(echo $TASK_DEFINITION | jq --arg IMAGE_URI "${{ steps.login-ecr.outputs.registry }}/ogata-cloudformation-template:latest" '.taskDefinition | .containerDefinitions[0].image=$IMAGE_URI | .cpu="512" | .memory="1024" | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
           echo $NEW_TASK_DEF > new-task-def.json
-          aws ecs register-task-definition --cli-input-json file://new-task-def.json
+          echo "Registering new task definition..."
+          aws ecs register-task-definition --cli-input-json file://new-task-def.json || { echo "Failed to register new task definition"; exit 1; }
+          echo "New task definition registered successfully."
 
       - name: Deploy to ECS
         env:
